[package]
name = "nonomura"
version = "0.1.0"
authors = ["Mariell Hoversholm <proximyst@proximyst.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
tokio-util = { version = "0.2", features = ["codec"] }
bytes = { version = "0.5", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
encoding = "0.2"
futures = "0.3"

failure = "0.1"

log = "~0.4"
simplelog = "~0.7"
