[package]
name = "nonomura"
version = "0.1.1"
authors = ["Mariell Hoversholm <proximyst@proximyst.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["full"] }

bytes = { version = "0.5", features = ["serde"] }
encoding = "0.2"
futures = "0.3"

serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"

failure = "0.1"

log = "~0.4"
simplelog = "~0.7"

parking_lot = "0.10"

[profile.release]
opt-level = 3
debug-assertions = false
overflow-checks = false
lto = true
debug = false
rpath = false
